### ISSUE TITLE
windows平台: filepacket received 然后弹出dogcom.exe已停止工作的对话框

### ISSUE THREAD

**Issue by mylight** [mchome/dogcom#1]
您好，我路由器cpu是arm的，openwrt系统，能不能帮忙编译一个程序呢？谢谢了。

**Comment by mchome** [comment]
你在其他平台确保能用么

**Comment by yujincheng08** [comment]
具体是哪一种平台？ARM也对应很多平台的呀！@mylight

**Comment by mylight** [comment]
linksys 1900acs Marvell芯片mvebu@yujincheng08

**Comment by mchome** [comment]
@mylight 你在linux或者windows里面运行正常么

**Comment by mylight** [comment]
之前用的https://github.com/drcoms/drcom-generic的D版文件，运行正常，就是路由器安装python感觉不稳定，安装python后运行一段时间不能正常重启。 @

**Comment by mchome** [comment]
我不是说那个项目，我是说这个项目

**Comment by mylight** [comment]
这个项目我没有测试，等回去了后我测试一下吧，现在没有测试环境。

**Comment by mylight** [comment]
ror_version = False这个项目的配置文件ror_version = False，是不是意味着ror_version = True的不可以使用？ @mchome

**Comment by mchome** [comment]
根据你抓的报文决定。

**Comment by mylight** [comment]
根据抓包文件得出的配置文件为
server = '1.1.3.8'
username=''
password=''
CONTROLCHECKSTATUS = '\x20'
ADAPTERNUM = '\x06'
host_ip = '172.24.64.206'
IPDOG = '\x01'
host_name = 'GILIGILIEYE'
PRIMARY_DNS = ''
dhcp_server = ''
AUTH_VERSION = '\x23\x00'
mac = 0xfcaa14297330
host_os = 'NOTE7'
KEEP_ALIVE_VERSION = '\xdc\x02'
ror_version = True

**Comment by mylight** [comment]
回去后测试一下吧。

**Comment by ly0** [comment]
`server = '1.1.3.8'` 这个不大对吧

**Comment by mylight** [comment]
对的，我们这边的server就是1.1.3.8，有线是1.1.1.8

**Comment by mylight** [comment]
windows客户端不能使用，提示338260784
filepacket received 然后弹出dogcom.exe已停止工作的对话框

**Comment by mchome** [comment]
原版客户端抓个包，附上账号密码

**Comment by mylight** [comment]
[55555.zip](https://github.com/mchome/dogcom/files/654467/55555.zip)
账号zhj19801022密码852512

**Comment by mylight** [comment]
你好，麻烦你有时间帮我看看我那个抓包文件，谢谢了！以前用的那个Python文件路由器经常出问题。 @mchome

**Comment by mchome** [comment]
忘记了把[recv_packet](https://github.com/mchome/dogcom/blob/master/keepalive.c#L146)拉大......

**Comment by mchome** [comment]
@mylight https://github.com/mchome/dogcom/releases/download/v1.1.0/dogcom-v1.1.1-mingw-x86_64.exe 试一下

**Comment by mylight** [comment]
非常感谢，已经休息了，明天早上试一下。

**Comment by mylight** [comment]
现在可以使用了，您修改下项目code吧。要是方便的话麻烦您帮我交叉编译个linksys 1900acs openwrt可以使用的版本吧，我不会搭建那个openwrt交叉编译环境。 @mchome

**Comment by mchome** [comment]
@mylight 你的openwrt版本呢，最好提供一下现成的sdk。等我把daemon做好就做openwrt包和luci包

**Comment by mylight** [comment]
我这里没有SDK，我是直接下载的固件刷的。我先自己研究下，看能不能搭建成功，谢谢了。这个不做daemon对程序的运行影响大吗？ @mchome

**Comment by mchome** [comment]
影响不大，只是防止重复运行而已

**Comment by mylight** [comment]
现在程序提示Failed to recv data：Result too large

**Comment by mylight** [comment]
@mchome

**Comment by mchome** [comment]
重新开个issue

**Comment by mylight** [comment]
我下载了那个openwrt sdk文件，可是编译还是不成功，是不是需要修改Makefile文件了。要是方便的话麻烦您帮我编译一下。sdk下载地址https://downloads.openwrt.org/chaos_calmer/15.05.1/mvebu/generic/OpenWrt-SDK-15.05.1-mvebu_gcc-4.8-linaro_uClibc-0.9.33.2_eabi.Linux-x86_64.tar.bz2 @mchome

**Comment by mchome** [comment]
https://github.com/mchome/dogcom/releases/download/v1.2.0/dogcom_v1.2.1-1_15.05.1_mvebu.ipk
试下

**Comment by mylight** [comment]
刚试了下，可以使用了。这个就是把源码都放在package文件夹下执行make就可以了？那个ccache安装了还是编译不了，能不能教我一下具体是怎么编译的吗？谢谢了。 @mchome

**Comment by mchome** [comment]
```bash
wget https://downloads.openwrt.org/chaos_calmer/15.05.1/mvebu/generic/OpenWrt-SDK-15.05.1-mvebu_gcc-4.8-linaro_uClibc-0.9.33.2_eabi.Linux-x86_64.tar.bz2 # 下载
tar -xjf OpenWrt-SDK-15.05.1-mvebu_gcc-4.8-linaro_uClibc-0.9.33.2_eabi.Linux-x86_64.tar.bz2 # 解压
cd OpenWrt-SDK-15.05.1-mvebu_gcc-4.8-linaro_uClibc-0.9.33.2_eabi.Linux-x86_64 # 进入目录
git clone https://github.com/mchome/openwrt-dogcom.git package/openwrt-drcom # 克隆项目
make package/openwrt-drcom/compile # 开始编译
scp bin/dogcom_v1.2.1-1_mvebu.ipk root@192.168.1.1:/tmp # 上传安装包到/tmp
```

**Comment by mylight** [comment]
@mchome 非常感谢！明天我试一下。

**Comment by mylight** [comment]
那个drcom客户端我弄好了，openwrt中稳定运行一整天，非常感谢你对我的帮助！@mchome
