### ISSUE TITLE
问题:

### ISSUE THREAD

**Issue by jackeyt** [mchome/dogcom#11]
1、这个支持x 版或者D版吗？
2、有openwrt版本的吗？或者用openwrt toolchain有编译过吗？

**Comment by autopanda** [comment]
1、有D版，X版大概不行。
2、你有看过README吗

**Comment by jackeyt** [comment]
1、你说是drcom-generic的C版，里面又有8021x，我以为X版没问题，然后明确支持版本也没说清楚呀？
2、README里面的openwrt版本链接过去后，里面只有一个配置文件跟makefile，你的意思是使用这两个代替即可?原谅理解能力不行。

**Comment by autopanda** [comment]
1、以tag v1.2.3为准，支持dhcp和pppoe。
2、你去搜一下怎么编译openwrt软件包吧。

**Comment by jackeyt** [comment]
OK   看到makefile的内容就了解了。
