### ISSUE TITLE
Build dogdom on macOS

### ISSUE THREAD

**Issue by stevapple** [mchome/dogcom#13]
Can anyone support the build of dogcom on macOS? Which libraries do I need to add manually and how to change the source for it? 
Thx for all your support.

**Comment by mchome** [comment]
I dont work with macos, but it seems to be built with `gcc` & `make` too. You can easily install them via brew.

**Comment by stevapple** [comment]
Thx for mchome, I supposed so. However, lib dependency and const check failed while make, which I'm now trying to fix.

**Comment by leetking** [comment]
@stevapple You may paste these message of buiding fail.
