### ISSUE TITLE
dogcom与py版在dhcp是不是有不一样的地方

### ISSUE THREAD

**Issue by 906596696** [mchome/dogcom#16]
大佬问个问题，py版的drcom，在我用mentohust获取到ip之后能正常登录，dogcom在同样的情况下不行，是不是因为-m 参数的dhcp的问题？

**Comment by mchome** [comment]
你用新版的看看有没有问题

**Comment by 906596696** [comment]
解决了，原来是因为用户名过长吗？还有大佬能不能通过mentohust的源码吧802.1x认证提取出来，融合到dogcom里呢

**Comment by mchome** [comment]
你试下`dogcom -m dhcp -c <FILEPATH> -x`

**Comment by 906596696** [comment]
并不行的，只有mentohust才能过那个802.1x，eap只有很少的x版能过

**Comment by mchome** [comment]
我这没测试环境所以没法弄，只能配合mentohust用了 :>

**Comment by mchome** [comment]
啊对了，如果你真的想要，@leetking 来维护802.1x :)

**Comment by leetking** [comment]
@906596696 难道不是802.1x认证成功，接口设置为dhcp获取，过段时间就能获到ip了。没有写dhcp协议的

**Comment by 906596696** [comment]
@leetking eap身份认证不成功，不过不知道你的是怎么弄的，可能我的有错

**Comment by 906596696** [comment]
@leetking 要怎么截呢？还有一个问题mentohust获取ip以后，是要继续发送心跳包的，我试过获取ip之后就停止，结果还是不行

**Comment by leetking** [comment]
这里实现的eap认证成功也会有心跳包。如果在电脑上操作，用 `wireshark` 就能抓取数据包。
`wireshark` 简易使用：
在没有登录时开启 `wireshark` 抓包，然后登录，成功或失败后一段时间，关闭 `wireshark` 并保存数据包。

**Comment by 906596696** [comment]
@leetking 这样是吗？这样我电脑还有数据包

**Comment by 906596696** [comment]
@leetking http://pan.baidu.com/s/1dEYhvP3之前抓下来的

**Comment by leetking** [comment]
如果有使用 `dogcom` 登录失败抓取的包就更好了On Jun 24, 2017 10:55 AM, 906596696 <notifications@github.com> wrote:@leetking http://pan.baidu.com/s/1dEYhvP3之前抓下来的

**Comment by 906596696** [comment]
@leetking 好的我去截一下给你

**Comment by 906596696** [comment]
@leetking 尴尬了，他们编译的电脑版dogcom没有x模式😂

**Comment by mchome** [comment]
@906596696 在路由器上，用tcpdump

**Comment by leetking** [comment]
我确认下，你是在 windows 下使用 dogcom？并且你做了如下尝试：
1. 使用 mentohust 来实现 802.1X认证，然后在使用 python版drcom 成功登录
２. 使用

**Comment by 906596696** [comment]
@leetking mentohust+dogcom已经成功了，失败的原因是我的账号太长了😂，我现在是想把mentohust认证802.1x的部分拿出来，融合到dogcom，那样dogcom就能解决所有x版了，http://pan.baidu.com/s/1bpEiO5D

**Comment by leetking** [comment]
@906596696 你说的 mentohust 是这个吗？（ https://github.com/hyrathb/mentohust ）我比对了下他实现的 eap 二者都是一样的，没发现问题。如果你能提供抓取这次包时的密码，我本地校验下最好。

**Comment by 906596696** [comment]
@leetking 大佬。要不加我qq讨论？mentohust差不多吧，不过我的更原始一点的版本，不知道区别大不大。mentohust会发送用户名和密码的，不知道你的有没有发送

**Comment by leetking** [comment]
可以，你留个联系

**Comment by 906596696** [comment]
@leetking 906596696
