### ISSUE TITLE
有没有整理drcom的通讯协议文档？

### ISSUE THREAD

**Issue by jackeyt** [mchome/dogcom#17]
虽然代码中有体现，但还是问一下有没有排版好的相关协议？

**Comment by mchome** [comment]
没有整理好的协议文档，你可以参照 [wireshark插件](https://github.com/drcoms/drcom-generic/blob/master/utils/drcom_2016.lua) 和 [latest-wired.py](https://github.com/drcoms/drcom-generic/blob/master/latest-wired.py) 整理一份。

**Comment by jackeyt** [comment]
噢，可惜~~有协议文档的话，方便交流，了解透彻些。

**Comment by de-conf** [comment]
> 噢，可惜~~有协议文档的话，方便交流，了解透彻些。

https://www.cnblogs.com/rainmote/p/4160549.html
