### ISSUE TITLE
参数获取错误

### ISSUE THREAD

**Issue by vc5** [mchome/dogcom#21]
`/usr/bin/dogcom -m dhcp -c /etc/dogcom.conf -l /tmp/dogcom.log -d -v`

按此执行命令,日志会输出到`/etc/dogcom.conf`

测试版本:1.5.0

**Comment by mchome** [comment]
呃，无法重现。但是你可以取消写log file。

**Comment by mchome** [comment]
不算是严重的问题，所以关闭这个issue了，如果有需要可以重开。

**Comment by vc5** [comment]
补充一点我这里的情况，我们学校用dogcom是可以正常上网的，但是会不定期进程死掉（python版相同症状），所以我写了个脚本检测进程存活，如果进程消失就自动重新登录
`/etc/dogcheck.sh`
```
#!/bin/sh

DOGCOMSTATUS=$(ps |grep dogcom |grep -v grep -c)
if [ "$DOGCOMSTATUS" = "0" ];then
	echo 'dog is gone,restarting...'
	/usr/bin/dogcom -m dhcp -c /etc/dogcom.conf  -l /tmp/dogcom.log -d -v
else
	echo 'dog is ok!!!'
fi
```

采用crontab定时运行
`* * * * * /bin/sh /etc/dogcheck.sh >>/tmp/dogcheck.log 2>&1`

然后就出现了日志会输出到/etc/dogcom.conf（我想看看日志为啥掉线）
