### ISSUE TITLE
keepalive1 第二种形式

### ISSUE THREAD

**Issue by lwxyl** [mchome/dogcom#22]
```
IPDOG = '\x01'
host_name = 'fuyumi'
PRIMARY_DNS = '10.10.10.23'
dhcp_server = '10.10.10.173'
AUTH_VERSION = '\x2f\x00'
mac = 0x0000d8cb8aef
host_os = 'Windows 10'
KEEP_ALIVE_VERSION = '\xdc\x02'
ror_version = True

You are binding at 0.0.0.0!

[Challenge sent] 010270b12f000000000000000000000000000000
[Challenge recv] 020270b10771040001000100f303e8f000000000ac1f24f4f000a8a80000e659f16700000000dc02000000800000000000000000000000000000000000000000000000000000000000000000
[Login sent] 0301001d20958b198ccfe4bb76d723a2b6f2b0ac3135303236303030340000000000000000000000000000000000000000000000000000002003209553d20620a374151b12fd73a4b8acaacd9932898301ac1f24690000000000000000000000006c1832beabf60aad0100000000667579756d6900000000000000000000000000000000000000000000000000000a0a0a170a0a0aad000000000000000000000000940000000500000001000000280a00000200000057696e646f7773000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002f00000abbd67ee20e34020c104fb52f00000000d8cb8aef0000e913
[login recv] 05000005150000000000000000000000000000006c6461702061757468206572726f720000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
<<< Logged in >>>
<<< login failed >>>
Retrying...
[Challenge sent] 01024b692f000000000000000000000000000000
[Challenge recv] 02024b690771040001000100f303e8f000000000ac1f24f4f000a8a80000e659f16700000000dc02000000800000000000000000000000000000000000000000000000000000000000000000
[Login sent] 0301001d20958b198ccfe4bb76d723a2b6f2b0ac3135303236303030340000000000000000000000000000000000000000000000000000002003209553d20620a374151b12fd73a4b8acaacd9932898301ac1f24690000000000000000000000006c1832beabf60aad0100000000667579756d6900000000000000000000000000000000000000000000000000000a0a0a170a0a0aad000000000000000000000000940000000500000001000000280a00000200000057696e646f7773000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002f00000abbd67ee20e34020c104fb52f00000000d8cb8aef0000e913
[login recv] 05000005150000000000000000000000000000006c6461702061757468206572726f720000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
<<< Logged in >>>
<<< login failed >>>
Retrying...
[Challenge sent] 01028ddc2f000000000000000000000000000000
[Challenge recv] 02028ddc0e71040001000100f303e8f000000000ac1f24f4f000a8a80000e659f16700000000dc02000000800000000000000000000000000000000000000000000000000000000000000000
[Login sent] 0301001d1a56a2661645b72948e44004f41bd13231353032363030303400000000000000000000000000000000000000000000000000000020031a567aad9caa69822dac38951b0cdce0f5da48ac18e801ac1f24690000000000000000000000004b1ce73ab55806530100000000667579756d6900000000000000000000000000000000000000000000000000000a0a0a170a0a0aad000000000000000000000000940000000500000001000000280a00000200000057696e646f7773000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002f00000a6ac83719da60020c007bf04f00000000d8cb8aef0000e913
[login recv] 05000005150000000000000000000000000000006c6461702061757468206572726f720000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
<<< Logged in >>>
<<< login failed >>>
Retrying...
[Challenge sent] 0102f8ec2f000000000000000000000000000000
[Challenge recv] 0202f8ec0e71040001000100f303e8f000000000ac1f24f4f000a8a80000e659f16700000000dc02000000800000000000000000000000000000000000000000000000000000000000000000
[Login sent] 0301001d1a56a2661645b72948e44004f41bd13231353032363030303400000000000000000000000000000000000000000000000000000020031a567aad9caa69822dac38951b0cdce0f5da48ac18e801ac1f24690000000000000000000000004b1ce73ab55806530100000000667579756d6900000000000000000000000000000000000000000000000000000a0a0a170a0a0aad000000000000000000000000940000000500000001000000280a00000200000057696e646f7773000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002f00000a6ac83719da60020c007bf04f00000000d8cb8aef0000e913
[login recv] 05000005150000000000000000000000000000006c6461702061757468206572726f720000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
<<< Logged in >>>
<<< login failed >>>
Retrying...
[Challenge sent] 0102f5722f000000000000000000000000000000
[Challenge recv] 0202f5721871040001000100f303e8f000000000ac1f24f4f000a8a80000e659f16700000000dc02000000800000000000000000000000000000000000000000000000000000000000000000
[Login sent] 0301001da35533c2b5d366825355c1dbbf5862853135303236303030340000000000000000000000000000000000000000000000000000002003a355eb093f3cfdad95099021ed05a42db37e5cac3b5a01ac1f2469000000000000000000000000064f6af82093be580100000000667579756d6900000000000000000000000000000000000000000000000000000a0a0a170a0a0aad000000000000000000000000940000000500000001000000280a00000200000057696e646f7773000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002f00000aa7d0bb3cc7d4020ca02a46cd00000000d8cb8aef0000e913
[login recv] 05000005150000000000000000000000000000006c6461702061757468206572726f720000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
<<< Logged in >>>
<<< login failed >>>
Retrying...
>>>>> Failed to keep in touch with server, exiting <<<<<
```

**Comment by mchome** [comment]
不清楚你用的是什么版本，请用新版本尝试。

**Comment by lwxyl** [comment]
我更新到了1.5.0，还改了mac，但登录后不能访问网络


Drcom-generic implementation in C.
Version: 1.5.0

Usage:
        dogcom -m <dhcp/pppoe> -c <FILEPATH> [options <argument>]...

Options:
        --mode <dhcp/pppoe>, -m <dhcp/pppoe>  set your dogcom mode
        --conf <FILEPATH>, -c <FILEPATH>      import configuration file
        --bindip <IPADDR>, -b <IPADDR>        bind your ip address(default is 0.0.0.0)
        --log <LOGPATH>, -l <LOGPATH>         specify log file
        --eternal, -e                         set eternal flag
        --verbose, -v                         set verbose flag
        --help, -h                            display this help






CONTROLCHECKSTATUS = '\x20'
ADAPTERNUM = '\x04'
host_ip = '172.31.36.105'
IPDOG = '\x01'
host_name = 'fuyumi'
PRIMARY_DNS = '10.10.10.23'
dhcp_server = '10.10.10.173'
AUTH_VERSION = '\x0d\x00'
mac = 0xd8cb8aef65b9
host_os = 'Windows 10'
KEEP_ALIVE_VERSION = '\xdc\x02'
ror_version = Ture

You are binding at 0.0.0.0!

Failed to bind socket: No error

C:\Users\WX> X:\Desktop\dogcom.exe -m dhcp -c X:\Desktop\drcom.conf -v
server = '10.10.10.5'
username = '150260004'
password = 'WODEMIMAHA'
CONTROLCHECKSTATUS = '\x20'
ADAPTERNUM = '\x04'
host_ip = '172.31.36.105'
IPDOG = '\x01'
host_name = 'fuyumi'
PRIMARY_DNS = '10.10.10.23'
dhcp_server = '10.10.10.173'
AUTH_VERSION = '\x0d\x00'
mac = 0xd8cb8aef65b9
host_os = 'Windows 10'
KEEP_ALIVE_VERSION = '\xdc\x02'
ror_version = Ture

You are binding at 0.0.0.0!

[Challenge sent] 0102c6bc0d000000000000000000000000000000
[Challenge recv] 0202c6bc7b81040001000100f303e8f000000000ac1aa0e2f000a8a80000e659f16700000000dc02000000800000000000000000000000000000000000000000000000000000000000000000
[Login sent] 0301001d1e1812a3501ba08d60f569cd7266625c3135303236303030340000000000000000000000000000000000000000000000000000002004c6d3984c35a2c354e449cb763961214da2df07b92b7b01ac1f24690000000000000000000000006c7a9a289332f8860100000000667579756d6900000000000000000000000000000000000000000000000000000a0a0a170a0a0aad000000000000000000000000940000000500000001000000280a00000200000057696e646f7773000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000d00020c6000b2fe0000d8cb8aef65b90000e913
[login recv] 04000005004a0d00001fb2a8037a030000ff00000000004472636f0a0a0a05d503ac1aa0e2018bb0050100010000000000000000000000011000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
<<< Logged in >>>
[Keepalive1 sent] ff1e1812a3501ba08d60f569cd7266625c0000004472636f0a0a0a05d503ac1aa0e2018b065600000000
Failed to recv data: No error
[Keepalive1 sent] ff1e1812a3501ba08d60f569cd7266625c0000004472636f0a0a0a05d503ac1aa0e2018bcc6500000000
Failed to recv data: No error
[Keepalive1 sent] ff1e1812a3501ba08d60f569cd7266625c0000004472636f0a0a0a05d503ac1aa0e2018b183a00000000
Failed to recv data: No error
[Keepalive1 sent] ff1e1812a3501ba08d60f569cd7266625c0000004472636f0a0a0a05d503ac1aa0e2018b1ad600000000
Failed to recv data: No error
[Keepalive1 sent] ff1e1812a3501ba08d60f569cd7266625c0000004472636f0a0a0a05d503ac1aa0e2018bfc2800000000
Failed to recv data: No error
[Keepalive1 sent] ff1e1812a3501ba08d60f569cd7266625c0000004472636f0a0a0a05d503ac1aa0e2018bb70300000000
Failed to recv data: No error
[Keepalive1 sent] ff1e1812a3501ba08d60f569cd7266625c0000004472636f0a0a0a05d503ac1aa0e2018ba6de00000000
Failed to recv data: No error
[Challenge sent] 0102c0ad0d000000000000000000000000000000
[Challenge recv] 0202c0ad8481040001000100f303e8f000000000ac1aa0e2f000a8a80000e659f16700000000dc02000000800000000000000000000000000000000000000000000000000000000000000000
[Login sent] 0301001dc668c086a003bb3a1bf86ed9ef1ca27a31353032363030303400000000000000000000000000000000000000000000000000000020041ea34a69c5ba2eea56d30aa9bde880d3c951d6a61b5b01ac1f246900000000000000000000000046240c8267af00240100000000667579756d6900000000000000000000000000000000000000000000000000000a0a0a170a0a0aad000000000000000000000000940000000500000001000000280a00000200000057696e646f7773000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000d00020ce0e952e40000d8cb8aef65b90000e913
[login recv] 04000005004b0d00001fb2a80378030000ff00000000004472636f0a0a0a05df03ac1aa0e20195b0050100010000000000000000000000011000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
<<< Logged in >>>
[Keepalive1 sent] ffc668c086a003bb3a1bf86ed9ef1ca27a0000004472636f0a0a0a05df03ac1aa0e20195a04600000000
Failed to recv data: No error
[Keepalive1 sent] ffc668c086a003bb3a1bf86ed9ef1ca27a0000004472636f0a0a0a05df03ac1aa0e20195c23500000000
Failed to recv data: No error
[Keepalive1 sent] ffc668c086a003bb3a1bf86ed9ef1ca27a0000004472636f0a0a0a05df03ac1aa0e2019597ee00000000
Failed to recv data: No error
[Keepalive1 sent] ffc668c086a003bb3a1bf86ed9ef1ca27a0000004472636f0a0a0a05df03ac1aa0e2019567b300000000
Failed to recv data: No error
[Keepalive1 sent] ffc668c086a003bb3a1bf86ed9ef1ca27a0000004472636f0a0a0a05df03ac1aa0e2019519b800000000
Failed to recv data: No error
[Keepalive1 sent] ffc668c086a003bb3a1bf86ed9ef1ca27a0000004472636f0a0a0a05df03ac1aa0e20195554300000000
Failed to recv data: No error
[Keepalive1 sent] ffc668c086a003bb3a1bf86ed9ef1ca27a0000004472636f0a0a0a05df03ac1aa0e201959dd300000000
Failed to recv data: No error
[Challenge sent] 0102539f0d000000000000000000000000000000
[Challenge recv] 0202539f8981040001000100f303e8f000000000ac1aa0e2f000a8a80000e659f16700000000dc02000000800000000000000000000000000000000000000000000000000000000000000000
[Login sent] 0301001d094d8fb7e9ea58cb96317fc8fc1893cd3135303236303030340000000000000000000000000000000000000000000000000000002004d18605588c53fcd8db3efc0a2a3a3ae60055d651d48b01ac1f2469000000000000000000000000a68741294e38488a0100000000667579756d6900000000000000000000000000000000000000000000000000000a0a0a170a0a0aad000000000000000000000000940000000500000001000000280a00000200000057696e646f7773000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000d00020c2097e4870000d8cb8aef65b90000e913
[login recv] 04000005004c0d00001fb2a80377030000ff00000000004472636f0a0a0a05f003ac1aa0e201a6b0050100010000000000000000000000011000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
<<< Logged in >>>
[Keepalive1 sent] ff094d8fb7e9ea58cb96317fc8fc1893cd0000004472636f0a0a0a05f003ac1aa0e201a6c4e900000000
Failed to recv data: No error
[Keepalive1 sent] ff094d8fb7e9ea58cb96317fc8fc1893cd0000004472636f0a0a0a05f003ac1aa0e201a6adf300000000
Failed to recv data: No error
[Keepalive1 sent] ff094d8fb7e9ea58cb96317fc8fc1893cd0000004472636f0a0a0a05f003ac1aa0e201a6de9a00000000
Failed to recv data: No error
[Keepalive1 sent] ff094d8fb7e9ea58cb96317fc8fc1893cd0000004472636f0a0a0a05f003ac1aa0e201a6daec00000000
Failed to recv data: No error
[Keepalive1 sent] ff094d8fb7e9ea58cb96317fc8fc1893cd0000004472636f0a0a0a05f003ac1aa0e201a6b02a00000000
Failed to recv data: No error
[Keepalive1 sent] ff094d8fb7e9ea58cb96317fc8fc1893cd0000004472636f0a0a0a05f003ac1aa0e201a65d1200000000
Failed to recv data: No error
[Keepalive1 sent] ff094d8fb7e9ea58cb96317fc8fc1893cd0000004472636f0a0a0a05f003ac1aa0e201a6757600000000
Failed to recv data: No error
[Challenge sent] 0102e9590d000000000000000000000000000000
[Challenge recv] 0202e9599481040001000100f303e8f000000000ac1f2469f000a8a80000e659f16700000000dc02000000800000000000000000000000000000000000000000000000000000000000000000
[Login sent] 0301001db73e9cbab4d30e9ee46a12e18fcf467131353032363030303400000000000000000000000000000000000000000000000000000020046ff51655d16aed51ed30b34e17d08f8c0b6e66bf804701ac1f2469000000000000000000000000db83d8e8b4475bc70100000000667579756d6900000000000000000000000000000000000000000000000000000a0a0a170a0a0aad000000000000000000000000940000000500000001000000280a00000200000057696e646f7773000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000d00020c00637c340000d8cb8aef65b90000e913
[login recv] 04000005004c0d00001fb2a80376030000ff00000000004472636f0a0a0a050104ac1f246901b7b0050100010000000000000000000000011000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
<<< Logged in >>>
[Keepalive1 sent] ffb73e9cbab4d30e9ee46a12e18fcf46710000004472636f0a0a0a050104ac1f246901b7222d00000000
Failed to recv data: No error
[Keepalive1 sent] ffb73e9cbab4d30e9ee46a12e18fcf46710000004472636f0a0a0a050104ac1f246901b7c8f200000000
Failed to recv data: No error
[Keepalive1 sent] ffb73e9cbab4d30e9ee46a12e18fcf46710000004472636f0a0a0a050104ac1f246901b7ee3c00000000
Failed to recv data: No error
[Keepalive1 sent] ffb73e9cbab4d30e9ee46a12e18fcf46710000004472636f0a0a0a050104ac1f246901b77e6700000000
Failed to recv data: No error
[Keepalive1 sent] ffb73e9cbab4d30e9ee46a12e18fcf46710000004472636f0a0a0a050104ac1f246901b7128a00000000
Failed to recv data: No error
[Keepalive1 sent] ffb73e9cbab4d30e9ee46a12e18fcf46710000004472636f0a0a0a050104ac1f246901b7a9e700000000
Failed to recv data: No error
[Keepalive1 sent] ffb73e9cbab4d30e9ee46a12e18fcf46710000004472636f0a0a0a050104ac1f246901b7cde600000000
Failed to recv data: No error

**Comment by lwxyl** [comment]
抓包文件 链接: https://pan.baidu.com/s/1i5L2XRf 密码: g624

**Comment by mchome** [comment]
keepalive1有点奇怪的东西，需要点时间去拓展这部分。

**Comment by mchome** [comment]
1. 发送0800请求(`0701080001000000`)
2. 接收返回报文:获取seed([8-11])
3. 发送

| Size | Content | Meaning   |
|------|---------|-----------|
| 1    | 0xff    | header    |
| 7    | 0x00    | dummy     |
| 4    |         | seed      |
| 8    |         | unknown   |
| 16   |         | auth_info |
| 2    |         | time      |
4. 接收返回报文:获取seed([8-11])

**Comment by lwxyl** [comment]
呃，看不懂，还有救吗？
