### ISSUE TITLE
树莓派使用lede如何使用pppoe拨带\r\n的账号

### ISSUE THREAD

**Issue by wikeys** [mchome/dogcom#27]
硬件是树莓派3b+，刷入了lede。
在执行drcom -m pppoe -c /usr/drcom.conf 时候出现
root@LEDE:/# dogcom -m pppoe -c /usr/drcom.conf[  247.887575] smsc95xx 1-1.1:1.0                                                                                                              eth0: link up, 100Mbps, full-duplex, lpa 0x4DE1
[  248.049880] pppoe-wan: renamed from ppp0

Failed to recv data: Resource temporarily unavailable
Retrying...
[  254.292179] smsc95xx 1-1.1:1.0 eth0: hardware isn't capable of remote wakeup
[  254.368602] smsc95xx 1-1.1:1.0 eth0: hardware isn't capable of remote wakeup
[  256.155329] smsc95xx 1-1.1:1.0 eth0: link up, 100Mbps, full-duplex, lpa 0x4DE                                                                                                             1
[  259.535056] pppoe-wan: renamed from ppp0
Failed to recv data: Resource temporarily unavailable
Retrying...
[  265.832579] smsc95xx 1-1.1:1.0 eth0: hardware isn't capable of remote wakeup
[  265.908544] smsc95xx 1-1.1:1.0 eth0: hardware isn't capable of remote wakeup
smsc95xx 1-1.1:1.0 eth0: hardware isn't capable of remote wakeup
[  267.439206] smsc95xx 1-1.1:1.0 eth0: link up, 100Mbps, full-duplex, lpa 0x4DE1
Failed to recv data: Resource temporarily unavailable
Retrying...
[  271.104939] pppoe-wan: renamed from ppp0

Failed to recv data: Resource temporarily unavailable
Retrying...
[  277.392704] smsc95xx 1-1.1:1.0 eth0: hardware isn't capable of remote wakeup
[  277.468562] smsc95xx 1-1.1:1.0 eth0: hardware isn't capable of remote wakeup
[  278.999249] smsc95xx 1-1.1:1.0 eth0: link up, 100Mbps, full-duplex, lpa 0x4DE1
[  282.635081] pppoe-wan: renamed from ppp0
Failed to recv data: Resource temporarily unavailable
Retrying...
>>>>> Failed to keep in touch with server, exiting <<<<<

请问大神，这是由于这硬件原因还是什么情况？

**Comment by mchome** [comment]
网线没接好或没拨号

**Comment by wikeys** [comment]
网线插了，拨号始终不成功。莫非不能用插着转换器来拨号？

**Comment by mchome** [comment]
请你详尽地说清楚你要表达的东西。

**Comment by wikeys** [comment]
不好意思啊。
我现在是遇到了Failed to recv data: Resource temporarily unavailable这个错误。我确定网线是插好的，在电脑上能成功拨号，转到树莓派上就失败了。而拨号这里呢，我也在路由器管理界面将它设置为pppoe，也配置好了账号密码，不管是\r\n+学号还是直接学号的形式我都试过，但是还是无法成功拨号。

**Comment by mchome** [comment]
openwrt/ledepppoe的拨号问题请参考 https://github.com/drcoms/drcom-generic/wiki/%E5%85%B3%E4%BA%8EP%E7%89%88%E7%9A%84PPPoE%E6%8B%A8%E5%8F%B7%E9%97%AE%E9%A2%98

**Comment by wikeys** [comment]
#!/bin/sh
cp /lib/netifd/proto/ppp.sh /lib/netifd/proto/ppp.sh_bak
sed -i '/proto_run_command/i username=`echo -e "$username"`' /lib/netifd/proto/ppp.sh
sed -i '/proto_run_command/i password=`echo -e "$password"`' /lib/netifd/proto/ppp.sh
执行了这个脚本。还是没能拨号成功。

**Comment by wikeys** [comment]
network配置
config interface 'loopback'
        option ifname 'lo'
        option proto 'static'
        option ipaddr '127.0.0.1'
        option netmask '255.0.0.0'

config globals 'globals'
        option ula_prefix 'fdb1:2c9b:147f::/48'

config interface 'lan'
        option type 'bridge'
        option proto 'static'
        option ipaddr '192.168.1.1'
        option netmask '255.255.255.0'
        option ip6assign '60'

config interface 'wan'
        option macaddr '00:00:00:00:00:01'
        option ifname 'eth0'
        option _orig_ifname 'eth0'
        option _orig_bridge 'false'
        option proto 'pppoe'
        option password 'password'
        option ipv6 'auto'
        option username '\r\nusername'

**Comment by mchome** [comment]
![image](https://user-images.githubusercontent.com/7392658/37143338-d1e8d9c8-22f5-11e8-9661-9e6589b0d9c9.png)

**Comment by wikeys** [comment]
没得救了吗 ？😭
