### ISSUE TITLE
如何能让dogcom不会一直尝试登录

### ISSUE THREAD

**Issue by ryewen** [mchome/dogcom#28]
在寝室PC上挂着dogcom，然后，我想在教室用手机连wifi登录Drcom，却一直被寝室PC上的dogcom挤掉，怎么才能让dogcom不会一直尝试登录呢？

**Comment by vc5** [comment]
加上-e参数

**Comment by mchome** [comment]
加上-e就无限重试了，没加-e你需要撞掉dogcom5次，或者你端口映射让外网访问路由器ssh/luci关掉dogcom，你可以写个定时停用的脚本，到时间就重连。

如果觉得麻烦的话，用流量吧（逃

**Comment by ryewen** [comment]
试了一个粗暴的办法：
我在教室 手机登录Drcom
寝室PC提示
![qq 20180311143709](https://user-images.githubusercontent.com/20164660/37250506-b323304c-2539-11e8-9aab-4110da4ca706.png)

发现这个程序在6次的连接失败后，好像会重新登录Drcom。

![qq 20180311143300](https://user-images.githubusercontent.com/20164660/37250489-22d5881e-2539-11e8-9d76-cc00c310585a.png)

然后我把auth.c 文件里的第633行 改为 if (keepalive_try_counter >= 0) exit(0);
让程序只要有1次连接失败就退出关闭。就不会尝试登录，然后就不会我手机Drcom挤掉了。。。

**Comment by mchome** [comment]
https://gist.github.com/mchome/f73e91322991800ba30c7e49728677af

I posted a script which can shutdown dogcom process by HTTP.
Endpoint: http://openwrt.lan:12121/killdogcom

Build with go1.10:
`GOOS=linux GOARCH=mips GOMIPS=softfloat go build -ldflags "-s -w"` or
`GOOS=linux GOARCH=arm go build -ldflags "-s -w"`
