### ISSUE TITLE
登陆成功，也持续进行心跳发包，但是会出现2分钟断线 6.0D版

### ISSUE THREAD

**Issue by Tongxn** [mchome/dogcom#30]
今天校园网进行了一次更新，之前大概2月的drcom可以使用，今天更新后就只能登陆但是无法保持在线，我提交了抓包文件和我的配置文件及使用的是dogcom版本是2月更新的1.6.2版本

[drcom.zip](https://github.com/mchome/dogcom/files/2039889/drcom.zip)

**Comment by mchome** [comment]
先去尝试python版本，有问题先去那里发issue，修好了这里会同步的。

**Comment by mchome** [comment]
pin drcoms/drcom-generic#305
