### ISSUE TITLE
请问此版本如何当作吉大版登录 --mode 中没有static模式 pppoe和dhcp模式登录失败

### ISSUE THREAD

**Issue by ImFengLala** [mchome/dogcom#31]
// 这里的配置文件参考了https://github.com/drcoms/jlu-drcom-client/blob/master/newclient.py
PS C:\Users\Fengl\Downloads\dogcom-1.6.2> cat .\jlu.conf
server = '10.100.61.3'
username = '***'
password = '***'
CONTROLCHECKSTATUS = '\x20'
ADAPTERNUM = '\x03'
host_ip = '40.140.58.200'
IPDOG = '\x01'
host_name = 'LIYUANYUAN'
PRIMARY_DNS = '10.10.10.10'
dhcp_server = '0.0.0.0'
AUTH_VERSION = '\x68\x00'
mac = 0xf48e38e84672
host_os = 'Windows 10'
KEEP_ALIVE_VERSION = '\xDC\x02'
ror_version = True
keepalive1_mod = True
PS C:\Users\Fengl\Downloads\dogcom-1.6.2> .\dogcom.exe --mode dhcp --conf .\jlu.conf --bindip 49.140.58.200 --log ./log.txt
<<< Login failed >>>
[Tips] The client version is incorrect.
Retrying...
<<< Login failed >>>
[Tips] The client version is incorrect.
Retrying...
<<< Login failed >>>
[Tips] The client version is incorrect.
Retrying...
PS C:\Users\Fengl\Downloads\dogcom-1.6.2> .\dogcom.exe --mode static --conf .\jlu.conf --bindip 49.140.58.200 --log ./log.txt
unknown mode
PS C:\Users\Fengl\Downloads\dogcom-1.6.2> .\dogcom.exe --conf .\jlu.conf --bindip 49.140.58.200 --log ./log.txt
>>>>> Failed to keep in touch with server, exiting <<<<<

PS C:\Users\Fengl\Downloads\dogcom-1.6.2> .\dogcom.exe --mode pppoe --conf .\jlu.conf --bindip 49.140.58.200 --log ./log.txt
Failed to recv data: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
Failed to recv data: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
PS C:\Users\Fengl\Downloads\dogcom-1.6.2>

**Comment by ImFengLala** [comment]
看到在v1.6.2中有提到[protocol] compatible with JLU

**Comment by mchome** [comment]
去掉--bindip 49.140.58.200

**Comment by ImFengLala** [comment]
PS C:\Users\Fengl\Downloads\dogcom-1.6.2> .\dogcom.exe --mode dhcp --conf .\jlu.conf --log ./log.txt
Failed to bind socket: 通常每个套接字地址(协议/网络地址/端口)只允许使用一次。
PS C:\Users\Fengl\Downloads\dogcom-1.6.2> .\dogcom.exe --mode dhcp --conf .\jlu.conf --log ./log.txt
<<< Login failed >>>
[Tips] The client version is incorrect.
Retrying...
<<< Login failed >>>
[Tips] The client version is incorrect.
Retrying...
<<< Login failed >>>
[Tips] The client version is incorrect.
Retrying...
PS C:\Users\Fengl\Downloads\dogcom-1.6.2> .\dogcom.exe --mode pppoe --conf .\jlu.conf --log ./log.txt
Failed to recv data: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
Failed to recv data: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
PS C:\Users\Fengl\Downloads\dogcom-1.6.2> .\dogcom.exe --conf .\jlu.conf --log ./log.txt
>>>>> Failed to keep in touch with server, exiting <<<<<

PS C:\Users\Fengl\Downloads\dogcom-1.6.2>

还是不行

**Comment by mchome** [comment]
先等程序跑完，别按^C

**Comment by ImFengLala** [comment]
PS C:\Users\Fengl\Downloads\dogcom-1.6.2> .\dogcom.exe --mode dhcp --conf .\jlu.conf --log ./log.txt
<<< Login failed >>>
[Tips] The client version is incorrect.
Retrying...
<<< Login failed >>>
[Tips] The client version is incorrect.
Retrying...
<<< Login failed >>>
[Tips] The client version is incorrect.
Retrying...
Start JLU mode.
<<< Logged in >>>
可以啦 多谢啦
