### ISSUE TITLE
有会ndk的大佬尝试做一下arm框架的版本……

### ISSUE THREAD

**Issue by Thiasap** [mchome/dogcom#36]
想做arm版本的dogcom在手机上使用，虽然几乎用不到，但是我这破手机后台的哆点根本挂不住，十几分钟后后台就被杀了，很难受，ndk-build的话Android,mk不会用，arm-linux-gcc也不会用……

**Comment by mchome** [comment]
pc版的你能用吗

**Comment by Thiasap** [comment]
> pc版的你能用吗

能啊可我总不能大晚上也一直开着电脑开热点呀……我原本的想法是连上wifi自动执行登录的命令，断开就结束进程来着，现在哆点后台挂不住，打开也慢。
已经在向隔壁班的同学请教cygwin了，要是编译不出来我就放弃了

**Comment by de-conf** [comment]
改下makefile用arm编译器编译下不就得了

**Comment by Thiasap** [comment]
@de-conf 比如ArmDS-5？我回头试试，反正之前用什么arm-linux-gcc啥的都会报错

**Comment by de-conf** [comment]
你什么信息都不给怎么知道哪里错了，去读下提问的智慧

**Comment by de-conf** [comment]
如果是路由器，使用openwrt sdk构建编译，代码在另一个repo

**Comment by mchome** [comment]
试试 termux + clang

**Comment by Thiasap** [comment]
'''
/mnt/e/ndkpro/dogcom/jni$ make
arm-linux-gcc -std=gnu99 -Werror   -c -o eapol.o eapol.c
/usr/local/arm-linux-gcc-4.4.3/bin/.arm-none-linux-gnueabi-gcc: 1: /usr/local/arm-linux-gcc-4.4.3/bin/.arm-none-linux-gnueabi-gcc: Syntax error: "(" unexpected
<builtin>: recipe for target 'eapol.o' failed
make: *** [eapol.o] Error 2
'''
路由器搞好了，就是想弄个手机的，这个是在ubuntu里运行arm-linux-gcc的，Makefile我就改了“CC = arm-linux-gcc”，其他的没动，不知道这个有没有关系,makefile就学了一点东西
@de-conf

**Comment by Thiasap** [comment]
```
vi Makefile
$ make
clang    -c -o configparse.o configparse.c
clang    -c -o keepalive.o keepalive.c
clang    -c -o daemon.o daemon.c
daemon.c:89:9: warning: implicit declaration of
      function 'lockf' is invalid in C99
      [-Wimplicit-function-declaration]
    if (lockf(pid_file_handle, F_TLOCK, ...
        ^
1 warning generated.
clang    -c -o auth.o auth.c
clang    -c -o main.o main.c
In file included from main.c:11:
./eapol.h:35:19: error: use of undeclared
      identifier 'ETH_ALEN'
    uchar dst_mac[ETH_ALEN];
                  ^
./eapol.h:36:19: error: use of undeclared
      identifier 'ETH_ALEN'
    uchar src_mac[ETH_ALEN];
                  ^
main.c:68:21: warning: comparison of array
      'mode' not equal to a null pointer is
      always true
      [-Wtautological-pointer-compare]
                if (mode != NULL) {
                    ^~~~    ~~~~
main.c:86:21: warning: comparison of array
      'mode' not equal to a null pointer is
      always true
      [-Wtautological-pointer-compare]
                if (mode != NULL) {
                    ^~~~    ~~~~
main.c:126:9: warning: comparison of array
      'mode' not equal to a null pointer is
      always true
      [-Wtautological-pointer-compare]
    if (mode != NULL && file_path != NULL) {
        ^~~~    ~~~~
3 warnings and 2 errors generated.
make: *** [<builtin>: main.o] Error 1
$
```
报错信息@mchome 
之前在termux里用gcc也是这样，我是不是得先手动编译其它的文件最后再编译main.c……

**Comment by de-conf** [comment]
手机是aarch64架构吧！
另termux见
https://github.com/de-conf/termux-dogcom

**Comment by de-conf** [comment]
你看下报错信息也该知道是需要改动源码的吧！无语

**Comment by de-conf** [comment]
另请直接使用termux编译

**Comment by Thiasap** [comment]
哇我都没注意到这个项目谢谢大佬@de-conf，我尝试过了，但是好像当时也没改好，我就找到common.h里有一个注释掉的define，然后……好像更多报错了我就没继续搞了。编译好了谢谢拉
