### ISSUE TITLE
I'm built a Docker image of the dogcom (But it only support DHCP)

### ISSUE THREAD

**Issue by ghost** [mchome/dogcom#39]
构建了一个多架构的Docker容器，可以在RPI上使用（都是Linux的）.

目前只使用的是以下命令：

<code>$ dogcom -m dhcp -c dogcom.conf</code>

详情地址：https://hub.docker.com/r/cheyoust/dogcom

**Comment by de-conf** [comment]
建议构建RPM安装包而不是容器，没有必要
