### ISSUE TITLE
P版，linux平台，Failed to recv data: Resource temporarily unavailable 以及 win平台 pppoe没反应

### ISSUE THREAD

**Issue by Git2Frank** [mchome/dogcom#5]
Failed to recv data: Resource temporarily unavailable

以下是log

```
[2017/01/04 Wed 16:18:37] [Challenge sent] 0700080001000000
[2017/01/04 Wed 16:18:37] [Challenge recv] 0700100002000000f7589906ac13da40a8a80000e659f16700000000dc020000
[2017/01/04 Wed 16:18:37] [PPPoE_login sent] 070160000300000000000000ac13da4000620014f75899063445b86c00000000000000000000008bac13da40ffffffff000000000000400000000000000000000000000000000000000000000000000000000000000000000000000000000000
[2017/01/04 Wed 16:18:40] [Challenge sent] 0702080001000000
[2017/01/04 Wed 16:18:40] [Challenge recv] 070210000200000012599906ac13da40a8a80000e659f16700000000dc020000
[2017/01/04 Wed 16:18:40] [PPPoE_login sent] 070360000300000000000000ac13da4000620014125999067ada8edd00000000000000000000008bac13da40ffffffff000000000000400000000000000000000000000000000000000000000000000000000000000000000000000000000000
[2017/01/04 Wed 16:18:43] [Challenge sent] 0704080001000000
[2017/01/04 Wed 16:18:43] [Challenge recv] 07041000020000002e599906ac13da40a8a80000e659f16700000000dc020000
[2017/01/04 Wed 16:18:43] [PPPoE_login sent] 070560000300000000000000ac13da40006200142e599906029059cb00000000000000000000008bac13da40ffffffff000000000000400000000000000000000000000000000000000000000000000000000000000000000000000000000000
```

在win10bash和ubuntu虚拟机里测试都是如上错误

配置是对的，python版成功

```
server = '172.24.253.35'
pppoe_flag = '\x14'
keep_alive2_flag = '\xdc'
```

**Comment by mchome** [comment]
发下python版的抓包

**Comment by ly0** [comment]
![image](https://cloud.githubusercontent.com/assets/1551736/21646123/d9e15eba-d2cf-11e6-96c4-6de8507bc703.png)

**Comment by mchome** [comment]
![wi 4qm 59 l2a 48w4 oj](https://cloud.githubusercontent.com/assets/7392658/21646181/1231ca2a-d2d0-11e6-95d7-3482c677b323.jpg)

**Comment by Git2Frank** [comment]
auth svr: 172.24.253.35
pppoe_flag: 14
keep_alive2_flag: dc
open local port:61440
DEBUG MODE:True
pppoe: send challenge request
	packet:0701080001000000
pppoe: received challenge response
	packet:070110000200000011f99c06ac13cfb3a8a80000e659f16700000000dc020000
pppoe: send heartbeat request
	packet:070260000300000000000000ac13cfb30062001411f99c064c613d9fd6309dcf00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
pppoe: heartbeat response failed, retry
pppoe: reset idx to 0x01
pppoe: send challenge request
	packet:0701080001000000
pppoe: received challenge response
	packet:07011000020000002cf99c06ac13cfb3a8a80000e659f16700000000dc020000
pppoe: send heartbeat request
	packet:070260000300000000000000ac13cfb3006200142cf99c060633322b0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
pppoe: received heartbeat response
	packet:0702300004002000c18ccc8a000000004439d8edcac0f74610002b62fc9d0442b0820060000000000000000000000000
[keep-alive2] send1
	packet:070028000b010f272f12000000000000000000000000000000000000000000000000000000000000
[keep-alive2] recv file, resending..
[keep-alive2] send1
	packet:070128000b01dc022f12000000000000000000000000000000000000000000000000000000000000
[keep-alive2] recv1
	packet:070128000b02dc022f120000000000002cf99c060000000000000000000000000000000000000000
[keep-alive2] send2
	packet:070128000b01dc022f12000000000000000000000000000000000000000000000000000000000000
[keep-alive2] recv2
	packet:070128000b02dc022f120000000000002cf99c060000000000000000000000000000000000000000
[keep-alive2] send3
	packet:070228000b03dc022f120000000000002cf99c06c72f31017e000000000000000000000000000000
[keep-alive2] recv3
	packet:070228000b04dc022f120000000000002cf99c060000000000000000000000000000000000000000
[keep-alive2] keep-alive2 loop was in daemon.
[keep_alive2] send 3
	packet:070328000b01dc022f120000000000002cf99c060000000000000000000000000000000000000000
[keep_alive2] recv
	packet:070328000b02dc022f120000000000002df99c060000000000000000000000000000000000000000
[keep_alive2] send 4
	packet:070428000b03dc022f120000000000002df99c068d3b71a27e71f22d000000000000000000000000
[keep_alive2] recv
	packet:070428000b04dc022f120000000000002df99c060000000000000000000000000000000000000000
pppoe: send challenge request
	packet:0702080001000000
pppoe: received challenge response
	packet:07021000020000008af99c06ac13cfb3a8a80000e659f16700000000dc020000
pppoe: send heartbeat request
	packet:070360000300000000000000ac13cfb3006300148af99c060a0a832e508b87a600000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
pppoe: heartbeat response failed, retry
pppoe: reset idx to 0x01
pppoe: send challenge request
	packet:0701080001000000
pppoe: received challenge response
	packet:0701100002000000a6f99c06ac13cfb3a8a80000e659f16700000000dc020000
pppoe: send heartbeat request
	packet:070260000300000000000000ac13cfb300620014a6f99c06d2ecc7aa20c757ab00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
pppoe: heartbeat response failed, retry
pppoe: reset idx to 0x01
pppoe: send challenge request
	packet:0701080001000000
pppoe: received challenge response
	packet:0701100002000000c2f99c06ac13cfb3a8a80000e659f16700000000dc020000
pppoe: send heartbeat request
	packet:070260000300000000000000ac13cfb300620014c2f99c0696c1f043eb72ff6f00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
pppoe: heartbeat response failed, retry

**Comment by Git2Frank** [comment]
win版：
>>>>> Failed to keep in touch with server, exiting <<<<<

**Comment by mchome** [comment]
怎么说呢，python版你有很多错误显示啊

**Comment by Git2Frank** [comment]
那咋整。。python版好歹能用

**Comment by mchome** [comment]
![qq 20170105134818](https://cloud.githubusercontent.com/assets/7392658/21670228/a686a394-d34d-11e6-84d1-3ffbbd2c3687.png)

**Comment by Git2Frank** [comment]
_(:з」∠)_

**Comment by mchome** [comment]
试下 [dogcom-MinGW-x86-64-v1.2.3](https://github.com/mchome/dogcom/releases/download/v1.0.0/dogcom-MinGW-x86-64-v1.2.3.exe).

**Comment by Git2Frank** [comment]
并不行。。还是老样子
`>>>>> Failed to keep in touch with server, exiting <<<<<`

**Comment by mchome** [comment]
把整段打出来....................................................................................................................................................

**Comment by mchome** [comment]
再试下，我改了

**Comment by Git2Frank** [comment]
`F:\drcoms>dogcom-MinGW -m pppoe -c sample-p.conf -l dogcom-MinGW.log -v
server = '172.24.253.35'
pppoe_flag = '\x14'
keep_alive2_flag = '\xdc'

>>>>> Failed to keep in touch with server, exiting <<<<<`

**Comment by mchome** [comment]
这是哪个的，我又重新传了

**Comment by Git2Frank** [comment]
MD5：	AA887872EB28FAE3A6829491939B44A4
最新的，没错吧。。

**Comment by mchome** [comment]
怎么练Challenge阶段也没了

**Comment by Git2Frank** [comment]
布吉岛_(:з」∠)_
拨号用你的pppoe-dialer拨的
要不要加个Q聊

**Comment by mchome** [comment]
群号 318495368
