### ISSUE TITLE
也许是个bug

### ISSUE THREAD

**Issue by leetking** [mchome/dogcom#6]
在auth.c的[358行](https://github.com/mchome/dogcom/blob/master/auth.c#L358)`sum = sum * 19680126 & 0xffffffff;`
如果工作在大端机器上结果也许会不同吧？

**Comment by ly0** [comment]
ntr快去兼容大端机 @mchome   
![image](https://cloud.githubusercontent.com/assets/1551736/23580251/9b3073da-0138-11e7-930f-4cc7bfd034fc.png)

**Comment by mchome** [comment]
![_sn2 a co7exc l_f l1](https://cloud.githubusercontent.com/assets/7392658/23580259/ab81fda8-0138-11e7-82de-15a6a762e86a.jpg)

**Comment by leetking** [comment]
路由器上大端不是很常见啊

**Comment by mchome** [comment]
op上的ar71xx是大端吧，跑过了没问题
